[random]
seed = 34141

[model]
num_nodes = 13
num_switches = 2
bandwidth = 500
capacity = 1500

[flow]
type = "gravity"  # "gravity", "uniform"
min_demand = 1
max_demand = 300
# uniform
num_flows = 8
sampling_demand_variance_percent=10
# Gravity
# Replaces num_flows
connection_percentage = 25
#  send_mass(m1)^power * recv_mass(m2)^power 
power = 2.0

[topology]
type = "rotating" # "rotating"
interval = 6
start_offset = 1

[schedule]
reschedule = false

[query]
sim_steps = 100  # Number of simulation steps for simulation queries.
sampling_steps = 150 # Number of simulation steps for the packet sampling queries.
sampling_count = 30 # Number of samples taken for the packet sampling queries.
sampling_earliest = 70 # Earliest step number (init steps excluded) that sampled packets may be introduced.
sampling_latest = 150 # Last step number (init steps excluded) that sampled packets may be introduced.
query_sim_packets_at_node = true
query_sim_packets_at_port = true
query_sim_max_sent = true
query_verify_check_overflow = false
query_sim_sampled_latency = true
query_sim_port_utilization = true

