[plotting]
packet_max = 5000
latency_max = 20
latency_avg = 8


[[instance]]
extension_name = "libfixed.so"
folder_name = "fixed_fewest"
modes = ["simulation", "verification"]
[instance.envs]
CHOICE_APPROACH = "FEWEST_HOPS"

[[instance]]
extension_name = "libfixed.so"
folder_name = "fixed_quickest"
modes = ["simulation", "verification"]
[instance.envs]
CHOICE_APPROACH = "QUICKEST"

[[instance]]
extension_name = "libvaliant.so"
folder_name = "valiant_quickest"
modes = ["simulation", "smc"]

[[instance]]
extension_name = "librotor_lb.so"
folder_name = "rotorlb"
modes = ["simulation", "verification"]
[instance.envs]
CHOICE_APPROACH = "UNIFORM"

[[instance]]
extension_name = "librotor_lb.so"
folder_name = "rotorlb_quickest"
modes = ["simulation", "verification"]
[instance.envs]
CHOICE_APPROACH = "QUICKEST"
