[plotting]
packet_max = 6100
latency_max = 40


[[instance]]
extension_name = "libfixed.so"
folder_name = "fixed_fewest"
reschedule = false
[instance.envs]
CHOICE_APPROACH = "FEWEST_HOPS"

[[instance]]
extension_name = "libfixed.so"
folder_name = "fixed_quickest"
reschedule = false
[instance.envs]
CHOICE_APPROACH = "QUICKEST"

[[instance]]
extension_name = "libvaliant.so"
folder_name = "valiant_quickest"
reschedule = false

[[instance]]
extension_name = "librotor_lb.so"
folder_name = "rotorlb"
reschedule = false
